### ISSUE TITLE
PythonBBS 请问是哪个项目?

### ISSUE THREAD

**Issue by hick** [9bie/go-telnet-bbs#1]
clone 下来发现是空目录,  搜过来发现我目的也跟你差不多, 是想练手一下 go , 
我另外一个目的是传统终端的字符界面 bbs  ,  可以的话麻烦回复告知下, 或者直接 email 发我:  hickwu at qq dot com

非常感谢

**Comment by 9bie** [comment]
https://gitee.com/gaoshi_team/PythonBBS

**Comment by hick** [comment]
收到, 非常感谢
